require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'bin/*'
    - 'Rakefile'

  DisplayCopNames: true

Metrics/LineLength:
  Max: 80
  IngorePatterns: ['(\A|\s)#']

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/FrozenStringLiteralComment:
  Safe: true
  SafeAutoCorrect: true
